# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/karchive' : '@stable'  
    'frameworks/kcompletion' : '@stable'
    'frameworks/kconfig' : '@stable'
    'frameworks/kconfigwidgets' : '@stable'
    'frameworks/kdnssd' : '@stable'
    'frameworks/kdeclarative' : '@stable'
    'frameworks/kguiaddons' : '@stable'
    'frameworks/kiconthemes' : '@stable'
    'frameworks/ki18n' : '@stable'
    'frameworks/knewstuff' : '@stable'
    'frameworks/kservice' : '@stable'
    'frameworks/kxmlgui' : '@stable'
    'frameworks/kwidgetaddons' : '@stable'
